Repository Kozea/WeasyPrint, pull requests merged in 2024-08, with the labels that each got.

#2208 Submit PDF forms
  tests/test_api.py
  weasyprint/css/html5_ua.css
  weasyprint/css/html5_ua_form.css
  weasyprint/formatting_structure/build.py
  weasyprint/pdf/anchors.py
Labels: feature

#2220 Add extra information to debug logs
  weasyprint/__main__.py
Labels: documentation

#2238 Set explicit flags when loading DLLs on Windows
  weasyprint/text/ffi.py
Labels: bug

#2231 Fix several problems related to flex-direction: column
  tests/layout/test_flex.py
  weasyprint/layout/flex.py
Labels: bug
