Repository Kozea/WeasyPrint, pull requests merged in 2025-01, with the labels that each got.

#2314 Use CSS 'image-rendering' attribute for images in SVGs
  tests/draw/svg/test_images.py
  weasyprint/svg/images.py
Labels: bug

#2343 Add support for outline-offset CSS property.
  docs/api_reference.rst
  tests/draw/test_box.py
  weasyprint/css/computed_values.py
  weasyprint/css/properties.py
  weasyprint/css/validation/properties.py
  weasyprint/draw/border.py
Labels: feature

#2341 Fix page groups
  tests/css/test_pages.py
  tests/layout/test_page.py
  tests/test_boxes.py
  weasyprint/css/__init__.py
  weasyprint/layout/page.py
Labels: bug

#2352 Update documentation
  docs/api_reference.rst
  docs/common_use_cases.rst
  docs/conf.py
  docs/first_steps.rst
  docs/index.rst
  pyproject.toml
Labels: documentation

#2361 Support text-underline-offset and text-decoration-thickness
  docs/api_reference.rst
  tests/css/test_expanders.py
  tests/draw/test_text.py
  weasyprint/css/__init__.py
  weasyprint/css/computed_values.py
  weasyprint/css/properties.py
  weasyprint/css/validation/expanders.py
  weasyprint/css/validation/properties.py
  weasyprint/draw/border.py
  weasyprint/draw/text.py
Labels: feature

#2338 custom RDF metadata for PDF/A, especially for Factur-X eInvoices
  docs/common_use_cases.rst
  tests/test_api.py
  tests/test_pdf.py
  weasyprint/__init__.py
  weasyprint/document.py
  weasyprint/pdf/__init__.py
  weasyprint/pdf/anchors.py
  weasyprint/pdf/metadata.py
Labels: feature

#2345 Handle small-caps synthesis
  docs/api_reference.rst
  tests/draw/test_text.py
  weasyprint/css/validation/expanders.py
  weasyprint/css/validation/properties.py
  weasyprint/draw/text.py
  weasyprint/pdf/anchors.py
  weasyprint/pdf/fonts.py
  weasyprint/pdf/stream.py
  weasyprint/text/constants.py
  weasyprint/text/ffi.py
  weasyprint/text/fonts.py
Labels: bug

#2364 Improve text layout heuristics and use layout log attributes
  weasyprint/text/ffi.py
  weasyprint/text/line_break.py
Labels: performance
