Repository Kozea/WeasyPrint, pull requests merged in 2025-05, with the labels that each got.

#2445 Add functionality to have additional http headers for url_fetcher
  weasyprint/urls.py
Labels: feature

#2439 Don’t rely on URL protocols outside URL fetcher function
  weasyprint/images.py
  weasyprint/urls.py
Labels: bug

#2447 Improve min- and max-content calculation
  tests/layout/test_preferred.py
  tests/test_text.py
  weasyprint/layout/inline.py
  weasyprint/layout/preferred.py
Labels: bug, sponsored
