Repository Kozea/WeasyPrint, pull requests merged in 2025-08, with the labels that each got.

#2535 Removed reference to defunct site in CSS documentation.
  docs/api_reference.rst
Labels: documentation

#2525 Various fixes for columns
  tests/layout/test_column.py
  tests/layout/test_footnotes.py
  weasyprint/layout/column.py
Labels: bug, sponsored

#2542 Don’t crash when lh and rlh are used for line height or font size
  tests/css/test_common.py
  weasyprint/css/computed_values.py
Labels: crash
